version: '3'

services:
  nginx:
    image: nginx:1.19.0
    ports:
      - 80:80
      - 3306:3306
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./stream.conf.d:/etc/nginx/stream.conf.d
    depends_on:
      - rest-api-1
      - rest-api-2
      - mysql1
      - mysql2
      - mysql-bkp
    networks:
      default:
        aliases:
          - nginx.example.docker
  
  rest-api-1:
    build:
      context: ./build/rest-api
    image: rest-api:0.1-wsgi
    networks:
      default:
        aliases:
          - server1.example.docker

  rest-api-2:
    build:
      context: ./build/rest-api
    image: rest-api:0.1-wsgi
    networks:
      default:
        aliases:
          - server2.example.docker

  mysql1:
    image: mysql:5.6
    networks:
      default:
        aliases:
          - mysql1.example.docker
    environment:
      MYSQL_ROOT_PASSWORD: nginx-cookbook
      MYSQL_DATABASE: nginx-cookbook
    volumes:
      - ./mysql-files/mysql1.sql:/docker-entrypoint-initdb.d/mysql1.sql

  mysql2:
    image: mysql:5.6
    networks:
      default:
        aliases:
          - mysql2.example.docker
    environment:
      MYSQL_ROOT_PASSWORD: nginx-cookbook
      MYSQL_DATABASE: nginx-cookbook
    volumes:
      - ./mysql-files/mysql2.sql:/docker-entrypoint-initdb.d/mysql2.sql
    
  mysql-bkp:
    image: mysql:5.6
    networks:
      default:
        aliases:
          - mysql-bkp.example.docker
    environment:
      MYSQL_ROOT_PASSWORD: nginx-cookbook
      MYSQL_DATABASE: nginx-cookbook
    volumes:
      - ./mysql-files/mysql-backup.sql:/docker-entrypoint-initdb.d/mysql-backup.sql
    

  tests:
    build:
      context: ./build/tests
    image: test:0.1
    depends_on:
      - nginx
    environment:
      NUMBER_OF_REQUESTS: 10
      SERVER_URL: http://nginx.example.docker